return {
    { 'a', 'Agenda' },
    { 'b', 'Microsoft Edge' },
    { 'c', 'Visual Studio Code' },
    { 'e', "Neovide" },
    { 'f', "Feishu" },
    { 'g', "GitButler" },
    { 'l', "Linear" },
    { 'k', "Timepage"},
    { 'm', "Mimestream" },
    { 'n', "Notion" },
    { 'o', "Obsidian" },
    { 'q', "QQ" },
    { 's', "System Preferences" },
    { 't', "Warp" },
    { 'w', "WeChat" },
}